<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e84b4268-51bd-4d07-b447-4dcd5ca88d51</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1b3uk2l')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1b3uk2l</value>
        <webElementGuid>af0d46a9-5f66-4afa-9253-4190be3c3d7b</webElementGuid>
    </webElementProperties>
</WebElementEntity>